local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

LSM:Register("statusbar","ElvUI Gloss", [[Interface\AddOns\ElvUI\media\textures\normTex.tga]])
LSM:Register("statusbar","ElvUI Norm", [[Interface\AddOns\ElvUI\media\textures\normTex2.tga]])
LSM:Register("background","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("border", "ElvUI GlowBorder", [[Interface\AddOns\ElvUI\media\textures\glowTex.tga]])
LSM:Register("font","ElvUI Font", [[Interface\AddOns\ElvUI\media\fonts\PT_Sans_Narrow.ttf]])
LSM:Register("font", "ElvUI Alt-Font", [[Interface\AddOns\ElvUI\media\fonts\Continuum_Medium.ttf]])
LSM:Register("font", "ElvUI Pixel", [[Interface\AddOns\ElvUI\media\fonts\Homespun.ttf]])
LSM:Register("font","ElvUI Combat", [[Interface\AddOns\ElvUI\media\fonts\Action_Man.ttf]])
LSM:Register("font","ElvUI Alt-Combat", [[Interface\AddOns\ElvUI\media\fonts\DieDieDie.ttf]])
LSM:Register("sound","ElvUI Warning", [[Interface\AddOns\ElvUI\media\sounds\warning.mp3]])
LSM:Register("sound","ElvUI Whisper", [[Interface\AddOns\ElvUI\media\sounds\whisper.mp3]])
-----------------
LSM:Register("border", "TP_HealthBarOverlayThin", [[Interface\AddOns\ElvUI\media\textures\TP_HealthBarOverlayThin.tga]])
LSM:Register("border", "TP_HealthBarHighlight", [[Interface\AddOns\ElvUI\media\textures\TP_HealthBarHighlight.tga]])
LSM:Register("border", "shadowBorder", [[Interface\AddOns\ElvUI\media\textures\shadowBorder.tga]])
LSM:Register("border", "shadowBorder2", [[Interface\AddOns\ElvUI\media\textures\shadowBorder2.tga]])
LSM:Register("border", "shadowBorder3", [[Interface\AddOns\ElvUI\media\textures\shadowBorder3.tga]])
LSM:Register("font","HauntAOE", [[Interface\AddOns\ElvUI\media\fonts\HauntAOE.ttf]])
LSM:Register("font","HOOGE", [[Interface\AddOns\ElvUI\media\fonts\HOOGE.TTF]])
LSM:Register("font","Arial Black", [[Interface\AddOns\ElvUI\media\fonts\ariblk.ttf]])
LSM:Register("font","Droid", [[Interface\AddOns\ElvUI\media\fonts\DROID.TTF]])
LSM:Register("sound","Cyclone", [[Interface\AddOns\ElvUI\media\sounds\Cyclone.mp3]])
LSM:Register("sound","Fear", [[Interface\AddOns\ElvUI\media\sounds\Fear.mp3]])
LSM:Register("sound","Hex", [[Interface\AddOns\ElvUI\media\sounds\Hex.mp3]])
LSM:Register("sound","MBurn", [[Interface\AddOns\ElvUI\media\sounds\MBurn.mp3]])
LSM:Register("sound","Mind Control", [[Interface\AddOns\ElvUI\media\sounds\MC.mp3]])
LSM:Register("sound","Poly", [[Interface\AddOns\ElvUI\media\sounds\Poly.mp3]])
LSM:Register("sound","Res", [[Interface\AddOns\ElvUI\media\sounds\Res.mp3]])
